const traitAbilities = {
  "Bg": {
    "Gray": { "ability": "Rage", "score": 1 },
    "Green": { "ability": "Sneak", "score": 1 },
    "Pink": { "ability": "Composure", "score": 1 },
    "Blue": { "ability": "Perception", "score": 1 },
    "Black": { "ability": "Fear", "score": 1 },
    "Yellow": { "ability": "Morale", "score": 1 },
    "Violet": { "ability": "Cunning", "score": 1 },
    "Orange": { "ability": "Money", "score": 1 }
  },
  "Fur": {
    "Chrissaturn Bloody": { "ability": "Bloodlust", "score": 5 },
    "Solana": { "ability": "Cunning", "score": 4 },
    "Gold": { "ability": "Money", "score": 3 },
    "Galaxy": { "ability": "Composure", "score": 2 },
    "Magma": { "ability": "Badass", "score": 2 },
    "Neon Green": { "ability": "Morale", "score": 1 },
    "Red": { "ability": "Fear", "score": 1 },
    "Neon Blue": { "ability": "Perception", "score": 1 },
    "Neon Yellow": { "ability": "Rage", "score": 1 },
    "Blue": { "ability": "Morale", "score": 1 },
    "Gray": { "ability": "Rage", "score": 1 },
    "White": { "ability": "Sneak", "score": 1 },
    "Black": { "ability": "Fear", "score": 1 }
  },
  "Eyes": {
    "Zulp Robot Eyes and Ears": { "ability": "Perception", "score": 5 },
    "Duckzzy Eye Patch": { "ability": "Fear", "score": 5 },
    "Wacko Glowing Eyes": { "ability": "Rage", "score": 5 },
    "Wacko Motorcycle Glasses": { "ability": "Badass", "score": 5 },
    "Wacko Viperz": { "ability": "Perception", "score": 5 },
    "Duckzzy Scar": { "ability": "Bloodlust", "score": 4 },
    "Diamond Eyes": { "ability": "Money", "score": 4 },
    "Laser Eyes": { "ability": "Rage", "score": 4 },
    "Money Eyes": { "ability": "Money", "score": 3 },
    "Red Shades": { "ability": "Composure", "score": 2 },
    "Aviator Glasses": { "ability": "Composure", "score": 2 },
    "Designer Glasses": { "ability": "Cunning", "score": 2 },
    "Viper Shades": { "ability": "Composure", "score": 2 },
    "Stoner": { "ability": "Composure", "score": 2 },
    "Sunglasses": { "ability": "Fear", "score": 2 },
    "Reading Glasses": { "ability": "Cunning", "score": 2 },
    "Monocle": { "ability": "Money", "score": 2 },
    "Orange Eyes": { "ability": "Morale", "score": 1 },
    "Blue Eyes": { "ability": "Perception", "score": 1 },
    "Demon Eyes": { "ability": "Fear", "score": 1 },
    "Green Eyes": { "ability": "Sneak", "score": 1 }
  },
  "Clothing": {
    "La Armor": { "ability": "Badass", "score": 5 },
    "Marculino Outfit": { "ability": "Morale", "score": 5 },
    "Gumbaz Outfit": { "ability": "Fear", "score": 5 },
    "Jazz Double Jacket": { "ability": "Morale", "score": 5 },
    "Wacko Cyber Punk Jacket": { "ability": "Cunning", "score": 5 },
    "Wacko Pimp Coat": { "ability": "Composure", "score": 5 },
    "Jazz Leather Jacket": { "ability": "Badass", "score": 5 },
    "Chrissaturn Streetwear Jacket": { "ability": "Cunning", "score": 5 },
    "Wacko Sheep Coat": { "ability": "Sneak", "score": 5 },
    "Zen0 Mf Hoodie": { "ability": "Perception", "score": 5 },
    "Duckzzy Chain": { "ability": "Money", "score": 5 },
    "Duckzzy Body": { "ability": "Composure", "score": 5 },
    "Chrissaturn Varsity Jacket": { "ability": "Cunning", "score": 5 },
    "Wacko Scarf Suit": { "ability": "Badass", "score": 5 },
    "Jazz Fur Coat": { "ability": "Composure", "score": 5 },
    "Jshep Roman Armour": { "ability": "Bloodlust", "score": 5 },
    "Zulp Robot Arm And Heart Monitor": { "ability": "Perception", "score": 5 },
    "Chrissaturn Ninja Jacket": { "ability": "Rage", "score": 5 },
    "Scum Tilmatli": { "ability": "Bloodlust", "score": 5 },
    "Kings Mantle": { "ability": "Rage", "score": 4 },
    "White Hoodie Up": { "ability": "Sneak", "score": 4 },
    "Mcwolf Shirt": { "ability": "Rage", "score": 3 },
    "Silk Robe": { "ability": "Composure", "score": 3 },
    "Black Open Suit": { "ability": "Money", "score": 3 },
    "Red Open Suit": { "ability": "Money", "score": 3 },
    "Admiral Uniform": { "ability": "Cunning", "score": 3 },
    "Mummy Wrap": { "ability": "Fear", "score": 3 },
    "Formal Suit": { "ability": "Money", "score": 3 },
    "Prisoner Suit": { "ability": "Rage", "score": 3 },
    "Poncho": { "ability": "Morale", "score": 3 },
    "Turtle Neck": { "ability": "Fear", "score": 2 },
    "Dectetive Coat": { "ability": "Cunning", "score": 2 },
    "Tech Fleece": { "ability": "Fear", "score": 2 },
    "Black Hoodie Down": { "ability": "Sneak", "score": 2 },
    "Puffer Jacket": { "ability": "Fear", "score": 2 },
    "Bomber Jacket": { "ability": "Composure", "score": 2 },
    "Black Shirt": { "ability": "Fear", "score": 2 },
    "Floral Shirt": { "ability": "Morale", "score": 2 },
    "Green Hoodie Down": { "ability": "Sneak", "score": 2 },
    "Blue And Red Shirt": { "ability": "Morale", "score": 2 },
    "Tank Top": { "ability": "Bloodlust", "score": 2 },
    "White And Yellow Shirt": { "ability": "Morale", "score": 2 },
    "Polo Shirt": { "ability": "Composure", "score": 2 }
  },
  "Hat": {
    "Balaklava": { "ability": "Sneak", "score": 5 },
    "Zulp Green Candles": { "ability": "Money", "score": 5 },
    "Zen0 Mf Cap": { "ability": "Morale", "score": 5 },
    "La Helmet": { "ability": "Badass", "score": 5 },
    "Scum Horns": { "ability": "Fear", "score": 5 },
    "Gumbaz Hat": { "ability": "Fear", "score": 5 },
    "Scum Flame": { "ability": "Rage", "score": 5 },
    "Chrissaturn Japanese Hat": { "ability": "Rage", "score": 5 },
    "Chrissaturn Oni Mask": { "ability": "Fear", "score": 5 },
    "Marculino Hat": { "ability": "Morale", "score": 5 },
    "Duckzzy Hat": { "ability": "Sneak", "score": 5 },
    "Wacko Sheep Hat": { "ability": "Sneak", "score": 5 },
    "Jazz Headband": { "ability": "Rage", "score": 5 },
    "Scum Hat": { "ability": "Rage", "score": 5 },
    "Jazz Flap Cap": { "ability": "Badass", "score": 5 },
    "Crown": { "ability": "Money", "score": 4 },
    "Jazz Bucket Hat": { "ability": "Rage", "score": 4 },
    "Pharao Hat": { "ability": "Cunning", "score": 4 },
    "Sombrero": { "ability": "Morale", "score": 4 },
    "Bigbrain": { "ability": "Cunning", "score": 3 },
    "Mcwolf Visor": { "ability": "Rage", "score": 3 },
    "Trainer Hat": { "ability": "Cunning", "score": 3 },
    "Flame Bandana": { "ability": "Rage", "score": 3 },
    "Top Hat": { "ability": "Money", "score": 3 },
    "Cowboy Hat": { "ability": "Composure", "score": 3 },
    "Admiral Cap": { "ability": "Badass", "score": 3 },
    "Miner Hat": { "ability": "Sneak", "score": 3 },
    "Red Beanie": { "ability": "Badass", "score": 2 },
    "Black Bandana": { "ability": "Fear", "score": 2 },
    "Green Bandana": { "ability": "Sneak", "score": 2 },
    "Beret": { "ability": "Badass", "score": 2 },
    "White Bandana": { "ability": "Morale", "score": 2 },
    "Blue Bandana": { "ability": "Morale", "score": 2 },
    "Black Beanie": { "ability": "Badass", "score": 2 },
    "Visor": { "ability": "Morale", "score": 2 }
  },
  "Mouth": {
    "Duckzzy Pacifier": { "ability": "Composure", "score": 5 },
    "Money": { "ability": "Money", "score": 4 },
    "Blood": { "ability": "Bloodlust", "score": 3 },
    "Bane Mask": { "ability": "Fear", "score": 3 },
    "Cigar": { "ability": "Morale", "score": 1 },
    "Joint": { "ability": "Composure", "score": 1 },
    "Pipe": { "ability": "Composure", "score": 1 }
  },
  "Overhead": {
    "Zen0 Ufo": { "ability": "Perception", "score": 5 },
    "La Halo": { "ability": "Perception", "score": 5 },
    "Chrissaturn Saturn": { "ability": "Perception", "score": 5 },
    "Halo": { "ability": "Perception", "score": 3 },
    "Plumbob": { "ability": "Perception", "score": 2 }
  },
  "Accessory": {
    "Nose Ring": { "ability": "Bloodlust", "score": 3 },
    "Earing": { "ability": "Bloodlust", "score": 3 },
    "Stud": { "ability": "Bloodlust", "score": 3 },
    "Eyebrow Ring": { "ability": "Bloodlust", "score": 2 }
  }
};
window.traitAbilities = traitAbilities; // Global kapsamda erişilebilir